modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="twendyfourmod"
version="1.0.0"
displayName="Robert's TwendyFourMod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Robert, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.twendyfourmod]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"



